# Generated by Django 2.1 on 2018-11-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Email_id', models.EmailField(max_length=80)),
                ('Password', models.CharField(max_length=20)),
                ('ConfirmPassword', models.CharField(max_length=20)),
                ('Phonenumber', models.IntegerField()),
                ('Location', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Image', models.ImageField(blank=True, upload_to='profile_image')),
            ],
        ),
    ]
